<?php
require '../src/msword_add.php';
/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-05-19 at 12:49:00.
 */
class msword_addTest extends PHPUnit_Framework_TestCase {

    /**
     * @var msword_add
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new msword_add;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers msword_add::save
     * @covers msword_add::updateFile
     * @covers msword_add::getFile
     * @covers msword_add::open
     * @covers msword_add::getFile
     */
    public function testSave() {
        $dir = dirname(__FILE__);
        if(file_exists($dir.'/copy.docx'))  unlink($dir.'/copy.docx');
        copy($dir .'/Testafails.docx',$dir.'/copy.docx');
        $b = $this->object->open($dir .'/copy.docx');
        $this->assertTrue($b);     
        
        $b = $this->object->save();
        $this->assertTrue($b);
        
        $this->object->setReadOnly();      
        $this->assertContains('documentProtection',$this->object->settings);
        $this->assertContains('readOnly',$this->object->settings);

        $b = $this->object->save();
        $this->assertTrue($b);        
        
    }

}
